name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install libxml2 libxml2-dev
    - run: ./configure
    - run: make
    - uses: actions/upload-artifact@v2
      with:
        name: dia2code-linux
        path: ./dia2code
    - run: sudo make install
    - run: make check
    - name: php8 test
      run: bash -x ./tests/php8_test.sh
